module.exports = {
	'import/default': 'error',
	'import/export': 'error',
	'import/extensions': [ 'error', 'ignorePackages' ],
	'import/first': 'error',
	'import/named': 'error',
	'import/newline-after-import': 'error',
	'import/no-absolute-path': 'error',
	'import/no-amd': 'error',
	'import/no-commonjs': 'error',
	'import/no-cycle': [ 'error', {
		'ignoreExternal': true,
	} ],
	'import/no-default-export': 'error',
	'import/no-duplicates': 'error',
	'import/no-extraneous-dependencies': 'error',
	'import/no-named-as-default': 'error',
	'import/no-namespace': 'error',
	'import/no-self-import': 'error',
	'import/no-unused-modules': 'error',
	'import/order': [ 'error', {
		'groups': [ 'builtin', 'external', 'parent', 'sibling', 'index' ],
		'newlines-between': 'always',
	} ],
};
