module.exports = {
	'unicorn/better-regex': 'error',
	'unicorn/catch-error-name': [ 'error', {
		'name': 'err',
	} ],
	'unicorn/consistent-destructuring': 'error',
	'unicorn/consistent-function-scoping': 'error',
	'unicorn/custom-error-definition': 'error',
	'unicorn/error-message': 'error',
	'unicorn/expiring-todo-comments': [ 'error', {
		'allowWarningComments': true,
	} ],
	'unicorn/no-abusive-eslint-disable': 'error',
	'unicorn/no-array-for-each': 'error',
	'unicorn/no-array-push-push': 'error',
	'unicorn/no-array-reduce': 'error',
	'unicorn/no-instanceof-array': 'error',
	'unicorn/no-lonely-if': 'error',
	'unicorn/no-object-as-default-parameter': 'error',
	'unicorn/no-unused-properties': 'error',
	'unicorn/prefer-array-some': 'error',
	'unicorn/prefer-date-now': 'error',
	'unicorn/prefer-default-parameters': 'error',
	'unicorn/prefer-includes': 'error',
	'unicorn/prefer-number-properties': [ 'error', {
		'checkInfinity': false,
	} ],
	'unicorn/prefer-regexp-test': 'error',
	'unicorn/prefer-string-slice': 'error',
	'unicorn/prefer-string-starts-ends-with': 'error',
	'unicorn/prefer-type-error': 'error',
	'unicorn/throw-new-error': 'error',
};
